version: '3.8'

services:

  github-cache-server:
    build:
      context: services/github-cache-server
      args:
        - AUTH_KEY=password
    environment:
      ADMIN_USERNAME: tester
    container_name: act_server

  sonatype:
    image: sonatype/nexus3:3.49.0
    container_name: act_nexus
    environment:
      NEXUS_SECURITY_RANDOMPASSWORD: "false"  # Password fijo xK9#mP2@
    command: /data/init.sh
    volumes:
      - ./services/scripts/sonatype_init.sh:/data/init.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status"]
      interval: 10s
      timeout: 20s
      retries: 20

  gitserver:
    image: gitlab/gitlab-ce
    container_name: act_git
    ports:
      - "8000:80"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['initial_root_password'] = 'xK9#mP2@'
        gitlab_rails['store_initial_root_password'] = true
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.key"
    command: /data/init.sh
    volumes:
      - ./services/scripts/git_init.sh:/data/init.sh
      - ./services/gitserver:/scripts
    healthcheck:
      test: [ "CMD", "sh", "-c", "test -s /root/token || exit 1" ]
      interval: 10s
      timeout: 20s
      retries: 60
      start_period: 300s

  mockserver:
    build:
      context: ./services/mockserver
    container_name: act_mockserver
    command: >
      --disable-http
      --https-port 8443 
      --https-keystore /certs/mockserver.jks
      --verbose
    volumes:
      - "./services/mockserver:/home/wiremock"
    healthcheck:
      test: [ "CMD", "curl", "-k", "https://localhost:8443/__admin/mappings" ]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  default:
    name: act-test-network
    driver: bridge
