#!/bin/bash
set -e

if ! docker info >/dev/null 2>&1; then
  echo "Error: Docker is not running." >&2
  exit 1
fi

cd /test/scripts
tests=( ${@:-Test_*} )

for test_file in ${tests[@]}; do
  id=${test_file#Test_}
  echo "$id"
done
