name: Publish release
on:
#  push:
#    branches: [main]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  publish:
    if: github.event.pull_request.merged == true &&
      (startsWith(github.event.pull_request.head.ref, 'release/') 
      || startsWith(github.event.pull_request.head.ref, 'hotfix/'))
    steps:
      - run: echo hola