name: Create Release Branch
on:
  workflow_dispatch:

jobs:
  config:
    name: Maven Configuration
    uses: wakamiti/wakamiti-github-actions/.github/workflows/maven.yml@main
    secrets: inherit

  release:
    uses: wakamiti/wakamiti-github-actions/.github/workflows/release.yml@main
    needs: config
    secrets: inherit
