name: Validate Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  config:
    name: Maven Configuration
    uses: wakamiti/wakamiti-github-actions/.github/workflows/maven.yml@main
    secrets: inherit

  validate:
    name: Validate Code
    uses: wakamiti/wakamiti-github-actions/.github/workflows/validate.yml@main
    needs: config
    secrets: inherit
