#!/bin/bash
set -e

event="push"
workdir="snapshot"
data="push_main.json"
workflow="validate"

# --------------------------

setup() {
  echo "setup"
  cd /target/$1
  git checkout main
  echo "New line" >> CHANGELOG.md
  git add .
  git commit -m 'feat: added new line for test'
  git push --set-upstream local main
}

teardown() {
  cd /target/$1
  git fetch local develop
  if ! git diff --quiet local/main..local/develop; then
    echo "ERROR: branches main and develop are not equal"
    exit 1
  fi
}

# --------------------------

id=$(basename "$0")
id=${id#Test_}

/docker/prepare $workdir $id $workflow
setup $id
/docker/act $event $id $data $workflow
teardown $id
