#!/bin/bash
set -e

event="push"
workdir="release"
data="push_hotfix.json"
workflow="release"

# --------------------------

setup() {
  echo "setup"
  cd /target/$1
  git checkout -b hotfix/v0.0.1
  git commit --allow-empty -m "#ready"
  git push --set-upstream local hotfix/v0.0.1
}

teardown() {
  count=$(curl -s -X POST "http://localhost:8080/__admin/requests/count" \
    -H "Content-Type: application/json" \
    -d '{ "method": "POST", "urlPattern": "/api/v3/repos/.*/.*/pulls" }' | jq -r '.count')
  [ "$count" -ge 1 ] || { echo "ERROR: Pull Request not found"; exit 1; }
}

# --------------------------

id=$(basename "$0")
id=${id#Test_}

/docker/prepare $workdir $id $workflow
setup $id
/docker/act $event $id $data $workflow
teardown $id
