#!/bin/bash
set -e

event="pull_request"
workdir="release"
data="pull_request-release.json"
workflow="validate"

# --------------------------

setup() {
  echo "setup"
  cd /target/$1
  git checkout -b release/v0.0.1
  git push --set-upstream local release/v0.0.1
}

teardown() {
  :
}

# --------------------------

id=$(basename "$0")
id=${id#Test_}

/docker/prepare $workdir $id $workflow
setup $id
/docker/act $event $id $data $workflow
teardown
