#!/bin/bash
set -e

event="workflow_dispatch"
workdir="release"
data="workflow_dispatch-hotfix.json"
workflow="init_hotfix"

# --------------------------

setup() {
  :
}

teardown() {
  branch="hotfix/v0.0.2"
  cd /target/$1
  git checkout $branch
  git log --stat
  if ! git log -1 --pretty=%B | grep -q "Prepare for the next patch iteration v0.0.2"; then
    echo "ERROR: commit message does not contain 'Prepare for the next patch iteration v0.0.2'"
    exit 1
  fi
  hash1=$(git merge-base $branch main)
  hash2=$(git rev-parse main)
  if [ ! "$hash1" = "$hash2" ]; then
    echo "ERROR: the branch '$branch' does not originate from 'main'"
    exit 1
  fi
  if ! cat pom.xml | grep -q "<version>0.0.2-SNAPSHOT</version>"; then
    echo "ERROR: the pom file does not contain snapshot version"
    exit 1
  fi
}

# --------------------------

id=$(basename "$0")
id=${id#Test_}

/docker/prepare $workdir $id $workflow
setup $id
/docker/act $event $id $data $workflow
teardown $id
