#!/bin/bash
set -e

event="workflow_dispatch"
workdir="release"
data="workflow_dispatch-release.json"
workflow="release"

# --------------------------

setup() {
  echo "setup"
  cd /target/$1
  git checkout -b release/v0.0.1
  git push --set-upstream local release/v0.0.1
}

teardown() {
  count=$(curl -s -X POST "http://localhost:8080/__admin/requests/count" \
      -H "Content-Type: application/json" \
      -d '{ "method": "POST", "urlPattern": "/api/v3/repos/.*/.*/pulls" }' | jq -r '.count')
  [ "$count" -ge 1 ] || { echo "ERROR: Pull Request not found"; exit 1; }
}

# --------------------------

id=$(basename "$0")
id=${id#Test_}

/docker/prepare $workdir $id $workflow
setup $id
/docker/act $event $id $data $workflow
teardown $id
