#!/bin/bash
set -e

event="pull_request"
workdir="snapshot"
data="pull_request.json"
workflow="validate"

# --------------------------

setup() {
  :
}

teardown() {
  :
}

# --------------------------

id=$(basename "$0")
id=${id#Test_}

/docker/prepare $workdir $id $workflow
setup $id
/docker/act $event $id $data $workflow
teardown $id
