#!/bin/bash
set -e

event="push"
workdir="release"
data="push_develop.json"
workflow="snapshot"

# --------------------------

setup() {
  :
}

teardown() {
  :
}

# --------------------------

id=$(basename "$0")
id=${id#Test_}

/docker/prepare $workdir $id $workflow
setup $id
/docker/act $event $id $data $workflow
teardown $id
