name: Create Release Branch
on:
  push:
    branches: [ develop ]

jobs:

  commits:
    name: Check commit ready
    uses: wakamiti/wakamiti-github-actions/.github/workflows/commits.yml@main
    secrets: inherit
    with:
      ref: develop

  config_maven:
    name: Maven Configuration
    if: needs.commits.outputs.ready == 'true'
    uses: wakamiti/wakamiti-github-actions/.github/workflows/maven.yml@main
    secrets: inherit
    needs: commits

  status:
    uses: wakamiti/wakamiti-github-actions/.github/workflows/status.yml@main
    secrets: inherit
    needs: config_maven
    with:
      ref: develop

  init_release:
    uses: wakamiti/wakamiti-github-actions/.github/workflows/init_release.yml@main
    secrets: inherit
    needs: [config_maven, status]
    with:
      changelog: ${{ needs.status.outputs.changelog }}
      version: ${{ needs.status.outputs.version }}
      revision: ${{ needs.status.outputs.revision }}
      branch: develop
      type: release
