name: Publish release
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [closed]
#  push:
#    branches: [ main ]
#    paths:
#      - 'src/**'
#      - 'pom.xml'

jobs:
  config_maven:
    name: Maven Configuration
    #    if: github.event.pull_request.merged == true &&
    #      (startsWith(github.event.pull_request.head.ref, 'release/')
    #      || startsWith(github.event.pull_request.head.ref, 'hotfix/'))
    uses: wakamiti/wakamiti-github-actions/.github/workflows/maven.yml@main
    secrets: inherit
  validate_code:
    name: Validate Code
    uses: wakamiti/wakamiti-github-actions/.github/workflows/validate_code.yml@main
    needs: [config_maven]
    secrets: inherit
    with:
      extra_options: -Dsonar.branch.name=main
  status:
    uses: wakamiti/wakamiti-github-actions/.github/workflows/status.yml@main
    needs: [config_maven, validate_code]
    secrets: inherit
    with:
      branch: main
  deploy:
    name: Deploy Release
    uses: wakamiti/wakamiti-github-actions/.github/workflows/deploy.yml@main
    needs: [config_maven, status]
    secrets: inherit
    with:
      changelog: ${{ needs.status.outputs.changelog }}
      version: ${{ needs.status.outputs.version }}
