name: Create Release PR
on:
  workflow_dispatch:
    inputs:
      type:
        required: true
        description: "The release type"
        type: choice
        options:
          - release
          - hotfix

jobs:

  branch:
    name: Get branch name
    uses: wakamiti/wakamiti-github-actions/.github/workflows/branch.yml@main
    secrets: inherit
    with:
      type: ${{ github.event.inputs.type }}

  config_maven:
    name: Maven Configuration
    uses: wakamiti/wakamiti-github-actions/.github/workflows/maven.yml@main
    secrets: inherit
    needs: branch

  status:
    uses: wakamiti/wakamiti-github-actions/.github/workflows/status.yml@main
    secrets: inherit
    needs: [branch, config_maven]
    with:
      ref: ${{ needs.branch.outputs.branch }}

  pr:
    name: Pull Request
    uses: wakamiti/wakamiti-github-actions/.github/workflows/create_pr.yml@main
    secrets: inherit
    needs: [branch, status]
    with:
      head: ${{ needs.branch.outputs.branch }}
      changelog: ${{ needs.status.outputs.changelog }}
