# Workflow Name: Create Maven Config
# This GitHub Actions workflow generates and caches Maven settings for dependency management
# and artifact deployment to GitHub Packages and Sonatype repositories.

name: Create Maven Config
on:
  workflow_call:

jobs:
  config_maven:
    name: Configure
    runs-on: ubuntu-latest
    env:
      PACKAGES_URL: ${{ vars.PACKAGES_URL }}
    steps:
      # Step: Cache Maven settings
      # - Attempts to restore cached settings.xml file
      # - Cache key is based on file content
      - name: Cache Maven settings
        id: maven-cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/settings.xml
          key: settings-xml

      # Step: Create settings.xml
      # - Generates Maven settings if not found in cache
      # - Configures:
      #   * GitHub authentication credentials
      #   * Repository settings for snapshots
      #   * Plugin repository configuration
      #   * Wakamiti profile activation
      - name: Create settings.xml
        if: steps.maven-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOL
            <settings>
              <servers><server>
                <id>github</id><username>\${GITHUB_ACTOR}</username><password>\${GITHUB_TOKEN}</password>
              </server></servers>
              <profiles>
                <profile>
                  <id>wakamiti</id>
                  <repositories>
                    <repository>
                      <id>github</id>
                      <url>${PACKAGES_URL}/*</url>
                      <snapshots><enabled>true</enabled></snapshots>
                    </repository>
                  </repositories>
                  <pluginRepositories>
                    <pluginRepository>
                      <id>github</id>
                      <url>${PACKAGES_URL}/*</url>
                      <snapshots><enabled>true</enabled></snapshots>
                    </pluginRepository>
                  </pluginRepositories>
                </profile>
              </profiles>
              <activeProfiles><activeProfile>wakamiti</activeProfile></activeProfiles>
            </settings>
          EOL
