name: Create Maven Config
on:
  workflow_call:

jobs:
  config:
    name: Configure
    runs-on: ubuntu-latest
    env:
      SONATYPE_URL: ${{ vars.SONATYPE_URL }}
      PACKAGES_URL: ${{ vars.PACKAGES_URL }}
    steps:
      - name: Cache Maven settings
        id: maven-cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/settings.xml
          key: settings-xml-${{ hashFiles('setup/maven-config.json') }}

      - name: Create settings.xml
        if: steps.maven-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOL
            <settings>
              <servers><server>
                <id>github</id><username>\${GITHUB_ACTOR}</username><password>\${GITHUB_TOKEN}</password>
              </server></servers>
              <profiles>
                <profile>
                  <id>wakamiti</id>
                  <repositories>
                    <repository>
                      <id>central</id>
                      <url>${SONATYPE_URL}/*</url>
                      <snapshots><enabled>false</enabled></snapshots>
                    </repository>
                    <repository>
                      <id>github</id>
                      <url>${PACKAGES_URL}/*</url>
                      <snapshots><enabled>true</enabled></snapshots>
                    </repository>
                  </repositories>
                  <pluginRepositories>
                    <pluginRepository>
                      <id>central</id>
                      <url>${SONATYPE_URL}/*</url>
                      <snapshots><enabled>false</enabled></snapshots>
                    </pluginRepository>
                    <pluginRepository>
                      <id>github</id>
                      <url>${PACKAGES_URL}/*</url>
                      <snapshots><enabled>true</enabled></snapshots>
                    </pluginRepository>
                  </pluginRepositories>
                </profile>
              </profiles>
              <activeProfiles><activeProfile>wakamiti</activeProfile></activeProfiles>
            </settings>
          EOL
