#
# see: https://github.com/jetersen/ghaction.file.sync
#
name: Sincronizar Workflows
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/syncs.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: jetersen/ghaction.file.sync@v1
        with:
          appId: ${{ secrets.APP_ID }}
          privateKey: ${{ secrets.APP_KEY }}