name: Pull Request Test
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml
    with:
      repo: ${{ github.event.repository.name }}
      working-directory: test
    secrets: inherit
