name: Publish Snapshot
on:
  push:
    branches: [develop]

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml
    with:
      repo: ${{ github.event.repository.name }}
      working-directory: test
      analyze: false
    secrets: inherit

  deploy:
    name: Publish Snapshot Package
    needs: validate
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/snapshot.yml
    with:
      working-directory: test
    secrets: inherit