#
# This workflow validates the release version and changelog for a Maven/Java
# project.
#
on:
  workflow_call:
    inputs:

      # The branch to check out and analyze.
      branch:
        required: true
        type: string

      # The changelog file name.
      changelog:
        required: true
        type: string

      # The current version to validate.
      version:
        required: true
        type: string

jobs:
  validate_version:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.head_ref }}-validate-version
      cancel-in-progress: true
    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      # Checks out the repository code using the specified branch provided as
      # input.
      - uses: actions/checkout@v4
        with:
          ref: '${{ inputs.branch }}'

      # Sets up Java Development Kit (JDK) version 17 using the Temurin
      # distribution.
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # Caches Maven settings file to avoid re-downloading it.
      - name: Cache Maven settings
        uses: actions/cache@v4
        with:
          path: ~/.m2/settings.xml
          key: settings-xml

      # Caches Maven dependencies to reduce build time.
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      # This step performs several checks on the version and changelog:
      # - Verifies that the changelog contains an [unreleased] block.
      # - Ensures the version is not a SNAPSHOT.
      # - Checks that there is no existing git tag with the provided version.
      # - Runs Maven verification with the release profile.
      - name: Check version
        run: |
          if grep -iq "\[unreleased\]" ${{ inputs.changelog }}; then 
            echo "::error::${{ inputs.changelog }} must contain an [unreleased] block."
            exit 1
          fi
          if [[ ${{ inputs.version }} =~ -SNAPSHOT$ ]]; then
            echo "::error::Current version ${VERSION} is a snapshot."
            exit 1
          fi
          if git tag | grep -q "^v${{ inputs.version }}$"; then
            echo "::error::The tag v${{ inputs.version }} already exists."
            exit 1
          else
            echo "El tag v${TAG} no existe."
          fi
          mvn verify -Prelease
